export  const SAVE_HALF_TRAVEL= "SAVE_HALF_TRAVEL"
export const  ADD_TRAVEL =  "ADD_TRAVEL"
export const ADD_TRAVELS = 'ADD_TRAVELS'
export const ADD_USERS_WITH_TRAVELS = 'ADD_USERS_WITH_TRAVELS'
export const CONFIRMATION_ERROR = 'CONFIRMATION_ERROR'
export const ADD_UPDATED_TRAVEL = 'ADD_UPDATED_TRAVEL'
